[info]
twitter = "https://twitter.com/leitalhao"
github = "https://github.com/antonio-leitao"
scholar = "https://scholar.google.com/citations?user=kJStlYkAAAAJ&hl=en"

[[papers]]
title = "Social Learning across Cultural Boundaries in non-human Communication"
url = "https://arxiv.org/abs/2307.05304"
published = "ArXiv 2023"
topic = "ceti"
summary = "Using variable length Markov models for modeling whale vocalizaations, we found that clans with geographic proximity exhibit more similar vocal styles, indicating social learning between clans."

[[papers]]
title = "Topological expressive power of Neural Networks"
url = "https://openreview.net/forum?id=I44kJPuvqPD"
published = "NeurIPS 2020"
topic = "tda"
summary = "We propose a topological description of neural network expressive power: the topology of the space of decision boundaries realized by a neural architecture."

[[papers]]
title = "On the Topological Complexity of Decision Boundaries"
url = "https://meetings3.sis-statistica.org/index.php/sis2021/index/pages/view/book"
published = "SIS 2021"
topic = "tda"
summary = "Classifying two concentric circles is challenging not because they are circles, but because they are concentric. We study and argue that the topology of the decision boundary of a classification problem is the most natural measure of its intrinsic complexity."

##### PROJECTS #####
[[projects]]
name = "Jet"
url = "https://github.com/antonio-leitao/jet"
thumbnail = "jet"

[[projects]]
name = "Iconography"
url = "https://github.com/antonio-leitao/iconografia-portuguesa"
thumbnail = "iconography"

[[projects]]
name = "Tiny Docs"
url = "https://github.com/antonio-leitao/tinydocs"
thumbnail = "tinydocs"

[[projects]]
name = "VLMC"
url = "https://github.com/antonio-leitao/vlmc"
thumbnail = "vlmc"

[[projects]]
name = "DBSampler"
url = "https://github.com/antonio-leitao/dbsampler"
thumbnail = "dbsampler"

[[projects]]
name = "NAU"
url = "https://github.com/antonio-leitao/nau"
thumbnail = "nau"

[[projects]]
name = "Caravela"
url = "https://github.com/antonio-leitao/caravela"
thumbnail = "caravela"

[[projects]]
name = "Ark"
url = "https://github.com/antonio-leitao/ark"
thumbnail = "ark"

[[projects]]
name = "Press"
url = "https://github.com/antonio-leitao/printing-press"
thumbnail = "press"
