[[research]]
topic = "Topological Data Analysis"
description = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa perspiciatis libero necessitatibus provident qui rerum, eveniet ipsum magnam beatae doloribus, corporis nemo quisquam aliquam, excepturi repudiandae et at similique. Modi."

[[research.papers]]
title = "Topological expressive power of Neural Networks"
url = "https://www.w3schools.com/jsref/jsref_length_array.asp"
published = "NeurIPS 2020"

[[research.papers]]
title = "On the Topological Complexity of Decision Boundaries"
url = "someurl"
published = "NeurIPS 2020"

# [[research]]
# topic = "Natural Language Processing"
# description = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa perspiciatis libero necessitatibus provident qui rerum, eveniet ipsum magnam beatae doloribus, corporis nemo quisquam aliquam, excepturi repudiandae et at similique. Modi."

# [[research.papers]]
# title = "Topological expressive power of Neural Networks"
# url = "https://www.w3schools.com/jsref/jsref_length_array.asp"
# published = "NeurIPS 2020"

# [[research.papers]]
# title = "On the Topological Complexity of Decision Boundaries"
# url = "someurl"
# published = "NeurIPS 2020"

[[projects]]
name = "Jet"
url = "https://github.com/antonio-leitao/jet"
tech = "python"
abstract = "JET is a testing library for python aimed at being fast to set up, easy to use and above all pleasing to the eye. Because testing does not have to be a chore to set up, clutter the terminal or ugly to look at."
thumbnail = "jet"

[[projects]]
name = "Portuguese Iconography"
url = "https://github.com/antonio-leitao/iconografia-portuguesa"
tech = "web • database"
abstract = "Database of glyphs, motiffs and patterns from portuguese culture. The purpose of this project is to trace, catalogue and index them as well as to make this Iconography known to the world."
thumbnail = "iconography"

[[projects]]
name = "Component Library"
url = "https://antonio-leitao.github.io/components/"
tech = "web"
abstract = "A UI components library written in svelte. Mostly for personal use, experimentation, learning and documentation."
thumbnail = "components"

[[projects]]
name = "DB Sampler"
url = "https://github.com/antonio-leitao/dbsampler"
tech = "rust • python"
abstract = "Python library for efficient and exact sampling of the decision boundary of high dimensional classification problems (binary or multiclass)."
thumbnail = "dbsampler"
