[info]
twitter = "https://twitter.com/leitalhao"
github = "https://github.com/antonio-leitao"
scholar = "https://scholar.google.com/citations?user=kJStlYkAAAAJ&hl=en"

[[papers]]
title = "Time-optimal persistent homology representatives for univariate time series"
url = "https://arxiv.org/abs/2412.08209"
size = 30
published = "arXiv 2024"
topic = "tda"


[[papers]]
title = "Evidence of social learning across cultural boundaries in Sperm Whales"
url = "https://elifesciences.org/reviewed-preprints/96362"
size = 32
published = "eLife 2024"
topic = "ceti"

[[papers]]
title = "Topological expressive power of Neural Networks"
url = "https://openreview.net/forum?id=I44kJPuvqPD"
published = "NeurIPS 2021"
size = 10
topic = "tda"

[[papers]]
title = "On the Topological Complexity of Decision Boundaries"
url = "https://meetings3.sis-statistica.org/index.php/sis2021/index/pages/view/book"
published = "SIS 2020"
size = 8
topic = "tda"

##### PROJECTS #####
[[projects]]
name = "Bib"
url = "https://github.com/antonio-leitao/bib"
icon = "bib"
lang="rust"
summary = "CLI tool for organizing, searching and managing bibliography."
size=0.65

[[projects]]
name = "Jet"
url = "https://github.com/antonio-leitao/jet"
icon = "jet"
lang= "python"
summary = "Simple and beautiful testing library for python with very little else."
pip="jet-test"
size=0.7

[[projects]]
name = "Press"
url = "https://github.com/antonio-leitao/printing-press"
icon = "press"
lang = "rust"
summary = "Compile LaTeX projects from templates defined on your computer."
size=0.8

[[projects]]
name = "VLMC"
url = "https://github.com/antonio-leitao/vlmc"
icon = "vlmc"
lang = "rust"
summary = "Fast and efficient Rust implementation of Variable Length Markov Chains."
pip="vlmc"
size=0.8


[[projects]]
name = "Tiny Docs"
url = "https://github.com/antonio-leitao/tinydocs"
icon = "tinydocs"
lang = "python"
summary = "Auto doc of python directories that outputs a single .md file."
pip="tinydocs"
size=0.3

[[projects]]
name = "DBSampler"
url = "https://github.com/antonio-leitao/dbsampler"
icon = "dbsampler"
lang="python"
summary = "Python framework for sampling the decision boundary of classification problems."
pip="dbsampler"
size=1

[[projects]]
name = "TDA"
url = "https://github.com/antonio-leitao/topological-data-analysis"
icon = "tda"
lang="rust"
summary = "Optimized Topological Data Analysis library. Not limited to just H0 and H1."
pip="tda"
size=1

