[[2024]]
title = "Participated at NetsciX 2024 in Venice"
date = "Jan 22"
summary = ""
link = "https://netscix2024.netscisociety.org"

[[2024]]
title = "Published new paper"
subtitle = "Evidence of Social Learning across cultures in sperm whales"
date = "Jan 18"
summary = ""
link = ""
type = "paper"


[[2024]]
title = "Release new python package"
subtitle = "Heron: Topological data Analysis"
date = "Jan 15"
summary = ""
link = ""
type = "code"


[[2023]]
title = "Started PhD at Scuola Normale Superiore"
date = "Nov 1"

[[2023]]
title = "Presented at Netsci 2024 Vienna"
subtitle = "Results on social learning across cultures in sperm whale communications"
date = "Jul 10"
link = ""
type = "talk"

[[2021]]
title = "Paper Accepted at NeurIPS workshop"
subtitle = "Topological Expressive Power of Neural Networks"
date = "Dec 12"
summary = ""
link = ""
type = "paper"

[[2020]]
title = "Published first paper"
subtitle = "Topological Complexity of Decision Boundaries"
date = "Jun 20"
summary = ""
link = ""
type = "paper"
