[[2024.talk]]
title = "NetsciX 2024 Venice"
date = "Jan 22"
summary = ""

[[2024.paper]]
title = "Evidence of Social Learning across cultures in sperm whales"
date = "Jan 18"
summary = ""
link = ""


[[2024.code]]
title = "Heron: initial release"
date = "Jan 15"
summary = ""
link = ""


[[2023.info]]
title = "Started PhD at Scuola Normale Superiore"
date = "Nov 1"
summary = ""
link = ""

[[2023.info]]
title = "NetSci 2023 Vienna"
date = "Jul 10"
summary = "Presented the work on social learning acroos cultures in sperm whale communications"
link = ""

[[2021.paper]]
title = "Topological Expressive Power of Neural Networks"
date = "Dec 12"
summary = ""
link = ""

[[2020.paper]]
title = "Topological Complexity of Decision Boundaries"
date = "Jun 20"
summary = ""
link = ""
